[package]
name = "task2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "task1"
path = homework2/task1/src/main.rs
[[bin]]
name = "task2"
path = homework2/task2/src/main.rs
[dependencies]
